image: node:latest

build:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build
    - mv dist www
  artifacts:
    paths:
      - www

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip-cleanup
  artifacts:
    paths:
      - www
